# Generated by Django 3.0.2 on 2020-04-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('date_of_birth', models.CharField(blank=True, max_length=128)),
                ('country_of_recidence', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('city_of_recidence', models.CharField(max_length=128)),
                ('phone_no', models.CharField(max_length=15)),
                ('fav_gnr_writing', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('otp', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
