# Generated by Django 3.0.2 on 2020-04-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verif_usr', '0002_auto_20200415_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
