# Generated by Django 3.0.2 on 2020-04-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verif_usr', '0003_user_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
